server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers
          uri: lb://customers
          predicates:
            - Path=/customers/**
        - id: products
          uri: lb://products
          predicates:
            - Path=/products/**
        - id: shopping
          uri: lb://shopping
          predicates:
            - Path=/invoices/**