server:
  port: 8080

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

# Gateway config

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customers
          uri: lb://customers  # Llamarlo por el nombre del servicio en Eureka
          predicates:
            - Path=/customers/**
        - id: products
          uri: lb://products  # Llamarlo por el nombre del servicio en Eureka
          predicates:
            - Path=/products/**
        - id: shopping
          uri: lb://shopping  # Llamarlo por el nombre del servicio en Eureka
          predicates:
            - Path=/invoices/**

