server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JuanCamiloVanegasRodriguez/spring-microservices.git
          searchPaths: config-data
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t

